# Generated by Django 5.2.9 on 2026-01-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_booking_status_en_booking_status_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role_ru',
        ),
    ]
