# Generated by Django 5.2.9 on 2026-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0004_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('icon', models.ImageField(upload_to='icons_images')),
                ('property', models.ManyToManyField(to='airbnb_app.property')),
            ],
        ),
    ]
