# Generated by Django 5.2.9 on 2026-01-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0005_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_property', to='airbnb_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rules',
            field=models.ManyToManyField(related_name='rule_property', to='airbnb_app.rules'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='airbnb_app.property'),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_property', to='airbnb_app.property'),
        ),
    ]
