# Generated by Django 5.2.9 on 2026-01-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0006_alter_property_city_alter_property_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_property', to='airbnb_app.property'),
        ),
    ]
