# Generated by Django 5.2.9 on 2026-01-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0007_alter_review_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='rules',
            new_name='rules_name',
        ),
        migrations.RenameField(
            model_name='rules',
            old_name='rules_en',
            new_name='rules_name_en',
        ),
        migrations.RenameField(
            model_name='rules',
            old_name='rules_ru',
            new_name='rules_name_ru',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='airbnb_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rules',
            field=models.ManyToManyField(related_name='rules', to='airbnb_app.rules'),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='airbnb_app.property'),
        ),
    ]
